#!/usr/bin/env bash

# Detect which `ls` flavor is in use
unamestr=`uname`
if [[ $unamestr == 'Darwin' ]];then
    colorflag="-G"
else
    colorflag="--color=auto"
fi

alias py="ptpython"
alias pyi="ptipython"
alias nv="nvim"

alias l="ls -lf ${colorflag}"

alias la="ls -laF ${colorflag}"

alias ls="command ls ${colorflag}"

# Always enable colored `grep` output
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias gitlog="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
