" Eli's vimrc ಠ_ಠ
" TODO: Think about splitting this up into separate files
" set nocompatible
let g:mapleader = ','
let g:neovim2_venv=expand('~/venvs/neovim2/bin/python')
let g:neovim3_venv=expand('~/venvs/neovim3/bin/python')
let g:plugins_location=expand('~/.config/nvim/plugged')

augroup vimrc
    autocmd!
augroup END

if !empty(glob(g:neovim2_venv))
    let g:python_host_prog=g:neovim2_venv
endif

if !empty(glob(g:neovim3_venv))
    let g:python3_host_prog=g:neovim3_venv
endif

let plug_location='~/.vim/autoload/plug.vim'
if has('nvim')
    let plug_location='~/.local/share/nvim/site/autoload/plug.vim'
endif

if empty(glob(plug_location))
    execute 'silent !curl -fLo '. plug_location .' --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Plugins {
    call plug#begin(g:plugins_location)
        Plug 'airblade/vim-rooter'                      " Change pwd to root for a file
        Plug 'Chiel92/vim-autoformat'                   " autoformatter
        Plug 'christoomey/vim-tmux-navigator'           " Tmux naviation so I don't get carpal tunnel
        Plug 'ekalinin/Dockerfile.vim'                  " Dockerfile stuff
        Plug 'haya14busa/incsearch.vim'                 " Better searching
        Plug 'jiangmiao/auto-pairs'                     " Auto pair parens and brackets
        Plug 'jszakmeister/vim-togglecursor'            " Toggle cursor in insert mode
        Plug 'junegunn/goyo.vim'                        " 'focus' mode
        Plug 'mbbill/undotree'                          " Undo tree
        Plug 'mhinz/vim-signify'                        " Diff symbols
        Plug 'mhinz/vim-startify'                       " Nice start screen
        Plug 'morhetz/gruvbox'                          " Really nice colorscheme
        Plug 'nathanaelkane/vim-indent-guides'          " Indent Guides
        Plug 'neoclide/coc.nvim', {'branch': 'release'} " Auto-completion
        Plug 'powerline/fonts'                          " Powerline fonts for airline
        Plug 'ryanoasis/vim-devicons'                   " Dev-icons for nerdtree
        Plug 'schickling/vim-bufonly'                   " Close all buffers except one
        Plug 'preservim/nerdtree'                       " File tree viewer
        Plug 'tpope/vim-abolish'                        " Case insensitive search and replace
        Plug 'tpope/vim-commentary'                     " Comment all the things
        Plug 'tpope/vim-fugitive'                       " Git stuff (Mainly for :Gblame)
        Plug 'tpope/vim-sleuth'                         " Detect tabs / spaces
        Plug 'tpope/vim-surround'                       " Surround things with things
        Plug 'vim-airline/vim-airline'                  " Cool ass statusline
        Plug 'vimwiki/vimwiki'
        Plug 'Xuyuanp/nerdtree-git-plugin'              " Git plugin for nerdtree
        Plug 'fatih/vim-go', {'for': 'go'}              " Go specific dev tools
        Plug 'rust-lang/rust.vim', {'for': 'rust'}      " Rust tooling
        Plug 'hashivim/vim-terraform', {'for': 'tf'}    " Terraform tooling / linting
        Plug 'jvirtanen/vim-hcl', {'for': 'hcl'}
        Plug 'pprovost/vim-ps1', {'for': 'ps1'}

        Plug 'nvim-lua/popup.nvim'
        Plug 'nvim-lua/plenary.nvim'
        Plug 'nvim-telescope/telescope.nvim'
        Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
    call plug#end()

    " telescope.nvim {
        nnoremap <leader>ff <cmd>lua require('telescope.builtin').find_files({hidden = true})<cr>
        nnoremap <leader>fg <cmd>lua require('telescope.builtin').live_grep()<cr>
        nnoremap <leader>fb <cmd>lua require('telescope.builtin').buffers()<cr>
        nnoremap <leader>fh <cmd>lua require('telescope.builtin').help_tags()<cr>
    " }

    " vim-signify {
        set updatetime=100
    " }

    " coc {
    " }

    " vim-tmux-navigator {
        " Disable tmux navigator when zooming the Vim pane
        let g:tmux_navigator_disable_when_zoomed = 1
    " }

    " vim-bufonly {
        nnoremap <Leader>bo :Bufonly<CR>
    " }

    " incsearch.vim {
        " Set it so that we actually use the plugin
        map /  <Plug>(incsearch-forward)
        map ?  <Plug>(incsearch-backward)
        map g/ <Plug>(incsearch-stay)
        " Set it so that ugly search highlights automagically go away
        set hlsearch
        let g:incsearch#auto_nohlsearch = 1
        map n  <Plug>(incsearch-nohl-n)
        map N  <Plug>(incsearch-nohl-N)
        map *  <Plug>(incsearch-nohl-*)
        map #  <Plug>(incsearch-nohl-#)
        map g* <Plug>(incsearch-nohl-g*)
        map g# <Plug>(incsearch-nohl-g#)
    " }

    " indent-guides {
        let g:indent_guides_start_level = 2
        let g:indent_guides_guide_size = 1
        let g:indent_guides_enable_on_vim_startup = 1
    " }

    " vim-airline {
        let g:airline_theme='gruvbox'
        let g:airline_powerline_fonts = 1
        let g:airline#extensions#tabline#enabled = 1
        let g:airline_section_error = '%{airline#util#wrap(airline#extensions#coc#get_error(),0)}'
        let g:airline_section_warning = '%{airline#util#wrap(airline#extensions#coc#get_warning(),0)}'
    " }

    " NERDTree {
        map <C-e> :NERDTreeToggle<CR>
        map <Leader>e :NERDTreeFind<CR>
        map <Leader>nt :NERDTreeFind<CR>

        let g:NERDTreeShowBookmarks=1
        let g:NERDTreeIgnore=['\.py[cd]$', '\~$', '\.swo$', '\.swp$', '^\.git$', '^\.hg$', '^\.svn$', '\.bzr$', '^\.ropeproject$']
        let g:NERDTreeChDirMode=0
        let g:NERDTreeQuitOnOpen=0
        let g:NERDTreeMouseMode=2
        let g:NERDTreeShowHidden=1
        let g:NERDTreeKeepTreeInNewTab=1
        let g:nerdtree_tabs_open_on_gui_startup=0
    " }

    " UndoTree {
        nnoremap <Leader>u :UndotreeToggle<CR>
        let g:undotree_SetFocusWhenToggle=1
    " }

    " Git Fugitive {
        let g:has_fugitive=1
    " }

    " rainbow {
        let g:rainbow_active = 1
    " }

    " coc {
        " GoTo code navigation.
        nmap <silent> gd <Plug>(coc-definition)
        nmap <silent> gy <Plug>(coc-type-definition)
        nmap <silent> gi <Plug>(coc-implementation)
        nmap <silent> gr <Plug>(coc-references)
        " if $CONDA_PREFIX == ""
        "   let s:current_python_path=$CONDA_PYTHON_EXE
        " else
        "   let s:current_python_path=$CONDA_PREFIX.'/bin/python'
        " endif
        " call coc#config('python', {'pythonPath': s:current_python_path})
        " Use K to show documentation in preview window.
        nnoremap <silent> K :call <SID>show_documentation()<CR>

        function! s:show_documentation()
          if (index(['vim','help'], &filetype) >= 0)
            execute 'h '.expand('<cword>')
          elseif (coc#rpc#ready())
            call CocActionAsync('doHover')
          else
            execute '!' . &keywordprg . " " . expand('<cword>')
          endif
        endfunction

        " Use tab for trigger completion with characters ahead and navigate.
        " NOTE: There's always complete item selected by default, you may want to enable
        " no select by `"suggest.noselect": true` in your configuration file.
        " NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
        " other plugin before putting this into your config.
        inoremap <silent><expr> <TAB>
              \ coc#pum#visible() ? coc#pum#next(1) :
              \ CheckBackspace() ? "\<Tab>" :
              \ coc#refresh()
        inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

        " Make <CR> to accept selected completion item or notify coc.nvim to format
        " <C-g>u breaks current undo, please make your own choice.
        inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                                      \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

        function! CheckBackspace() abort
          let col = col('.') - 1
          return !col || getline('.')[col - 1]  =~# '\s'
        endfunction

        " Use <c-space> to trigger completion.
        if has('nvim')
          inoremap <silent><expr> <c-space> coc#refresh()
        else
          inoremap <silent><expr> <c-@> coc#refresh()
        endif
        " Use `[g` and `]g` to navigate diagnostics
        " Use `:CocDiagnostics` to get all diagnostics of current buffer in location list.
        nmap <silent> [g <Plug>(coc-diagnostic-prev)
        nmap <silent> ]g <Plug>(coc-diagnostic-next)
    " }

    " vim-go {
        let g:go_metalinter_autosave = 0
    " }

    " vim-terraform {
        let g:terraform_align=1
        let g:terraform_fmt_on_save=1
    " }

" }

" General {
    " Allow a trigger for the background
    set background=dark
    function! ToggleBG()
        let s:tbg = &background
        " Inversion
        if s:tbg ==# 'dark'
            set background=light
        else
            set background=dark
        endif
    endfunction
    nnoremap <Leader>bg :call ToggleBG()<CR>

    filetype plugin indent on       " Automatically detect file types.
    syntax on                       " Syntax highlighting
    set mousehide                   " Hide the mouse cursor while typing
    set encoding=utf8
    scriptencoding utf-8

    if has('nvim')
        set clipboard+=unnamedplus
    else
        set clipboard+=unnamed          " Enable clipboard from OSX
    endif
    set viewoptions=folds,options,cursor,unix,slash
    set virtualedit=onemore         " Allow for cursor beyond last character
    set history=1000                " Store a ton of history
    set nospell                     " Turn spellcheck off
    set hidden                      " Allow buffer switching without saving

    " Set it to the first line when editing a git commit message
    augroup gcommit
        au FileType gitcommit au! BufEnter COMMIT_EDITMSG call setpos('.', [0, 1, 1, 0])
    augroup END

    " Restore cursor to file position in previous editing session
    function! ResCur()
        if line("'\"") <= line("$")
            silent! normal! g`"
            return 1
        endif
    endfunction

    augroup resCur
        autocmd!
        autocmd BufWinEnter * call ResCur()
    augroup END

    " Sets central temp file location, to prevent local default behavior.
    if isdirectory($HOME . '/.vim/.tmp') == 0
        :silent !mkdir -m 700 -p ~/.vim/.tmp > /dev/null 2>&1
    endif

    set backupdir=~/.vim/.tmp ",~/.local/tmp/vim,/var/tmp,/tmp,
    set directory=~/.vim/.tmp ",~/.local/tmp/vim,/var/tmp,/tmp,

    if exists('+undofile')
        " undofile -- This allows you to use undos after exiting and
        "             restarting. NOTE: only present in 7.3+
        "             :help undo-persistence
        if isdirectory( $HOME . '/.vim/.undo' ) == 0
            :silent !mkdir -m 700 -p ~/.vim/.undo > /dev/null 2>&1
        endif
        set undodir=~/.vim/.undo
        set undofile
    endif
" }


" UI Options {
    if has('gui_running')
        set guioptions-=r
        set guioptions-=l
        set guioptions-=R
        set guioptions-=L
    endif
    " True color support
    set termguicolors

    color gruvbox

    set splitbelow
    set splitright
    set tabpagemax=15   " Only show 15 tabs
    set showmode        " Display the current mode
    if exists('&inccommand')
        set inccommand=split " Turn on live preview substitute
    endif

    highlight clear SignColumn
    highlight clear LineNr
    " Enable transparency
    highlight Normal ctermbg=none
    highlight NonText ctermbg=none

    if has('cmdline_info')
        set ruler
        set rulerformat=%30(%=\:b%n%y%m%r%w\ %l,%c%V\ %P%)
        set showcmd
    endif

    if has('statusline')
        set laststatus=2
        set statusline=%<%f\                    " Filename
        set statusline+=%w%h%m%r                " Options
        if g:has_fugitive == 1
            set statusline+=%{fugitive#statusline()}
        endif
        set statusline+=\ [%{&ff}/%Y]           " Filetype
        set statusline+=\ [%{getcwd()}]         " Current dir
        set statusline+=%=%-14.(%l,%cV%)\ %p%%  " Right aligned file nav info
    endif

    set backspace=indent,eol,start                  " Working backspace
    set number                                      " Line numbers are on
    set showmatch                                   " Show matching brackets/parenthesis
    set incsearch                                   " Find as you type search
    set ignorecase                                  " Case insensitive search
    set smartcase                                   " Case sensitive when uc present
    set wildmenu                                    " Show a list of completions for commands
    set wildmode=list:longest,full                  " Command <Tab> completion, list matches,then longest part, then all.
    set whichwrap=b,s,h,l,<,>,[,]                   " Backspace and cursor keys wrap too
    set scrolljump=5                                " Lines to scroll when cursor leaves screen
    set scrolloff=3                                 " Minimum lines to keep above/below cursor
    set list
    set listchars=tab:›\ ,trail:•,extends:#,nbsp:.  " Highlight problematic whitespace
    set foldmethod=indent
    set foldlevelstart=99
    autocmd vimrc FileType python let &colorcolumn=80
    " Disable the annoying bells
    set noerrorbells visualbell t_vb=
    if has('autocmd')
        autocmd vimrc GUIEnter * set visualbell t_vb=
    endif

    if has('nvim')
        au TermOpen * setlocal nonumber norelativenumber
    endif
" }

" Formatting {
    set nowrap          " No wrapping
    set autoindent      " Indent at the same level of the prev line
    set shiftwidth=4    " Use indents of 4 spaces
    set expandtab       " Tabs are spaces
    set tabstop=4       " An indentation every four columns
    set softtabstop=4   " Let backspace delete indent
    set nojoinspaces    " Prevents inserting two spaces after punctuation on a join (J)
    function! StripTrailingWhitespace()
        let l:_s=@/
        let l:l = line('.')
        let l:c = line('.')
        %s/\s\+$//e
        let @/=l:_s
        call cursor(l:l, l:c)
    endfunction
    " Deletes trailing whitespace
    nnoremap <Leader>sw :call StripTrailingWhitespace()<CR>
    autocmd vimrc FileType c,cpp,java,php,javascript,puppet,python,rust,twig,xml,yml,perl,sql,groovy,sh autocmd BufWritePre <buffer> :call StripTrailingWhitespace()
    " Auto put things to 2 spaces when doing haskell, puppet, ruby, yml
    autocmd vimrc FileType haskell,puppet,ruby,yml setlocal expandtab shiftwidth=2 softtabstop=2
" }

" Key Mappings {
    " Easier moving in tabs and windows
    nnoremap <C-J> <C-W>j   " Move up
    nnoremap <C-K> <C-W>k   " Move down
    nnoremap <C-L> <C-W>l   " Move left
    nnoremap <C-H> <C-W>h   " Move right

    " Easier moving in tabs
    map <S-H> gT
    map <S-L> gt

    " Change working directory to that of the current file
    cmap cwd lcd %:p:h
    cmap cd. lcd %:p:h

    " Adjust viewports to the same size
    map <Leader>= <C-w>=

    " Easy horizontal scrolling
    map zl zL
    map zh zH

    " Easier indenting
    vmap q <gv
    vmap <TAB> >gv
" }

