# Path stuff
export PATH="$PATH:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki"
export PATH=/usr/local/lib:$PATH
export TERM="xterm-256color"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
else
  export EDITOR='nvim'
fi

# Aliases
alias nv="nvim"
alias py="ptpython"
alias pyclean='find . -name "*.pyc" -delete'
alias k='k -h'
alias c='clear'
alias grep='grep --color=auto'
alias gitlog="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"

# Plugins stuff
# load zplug if it doesn't exist
[[ -d ~/.zplug ]] || {
    git clone https://github.com/b4b4r07/zplug ~/.zplug
}
source ~/.zplug/init.zsh
# Hacky way to load oh-my-zsh libs
zplug "robbyrussell/oh-my-zsh", use:"lib/*.zsh", nice:-19
# Install plugins
zplug "plugins/pyenv",      from:oh-my-zsh, if:"which pyenv"
zplug "plugins/pip",        from:oh-my-zsh, if:"which pip"
zplug "plugins/brew",       from:oh-my-zsh, if:"which brew"
zplug "plugins/git",        from:oh-my-zsh, if:"which git"
zplug "plugins/extract",    from:oh-my-zsh
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-syntax-highlighting"
zplug "rimraf/k"
# Theme!
zplug "denysdovhan/spaceship-zsh-theme"
# Actually install plugins, prompt user input
if ! zplug check --verbose; then
    printf "Install zplug plugins? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi
zplug load --verbose

# source fzf if it exists
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source ~/.aliases
