# Set history size
HISTSIZE=1000
SAVEHIST=1000

# UNCOMMENT TO BENCHMARK
# BENCHMARK=1 && zmodload zsh/zprof

# Path stuff
export PATH="/usr/local/lib:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:$PATH"
export TERM="xterm-256color"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
    export EDITOR='nvim'
else
    export EDITOR='nvim'
fi

# Aliases
alias nv="nvim"
alias py="ptpython"
alias pyclean='find . -name "*.pyc" -delete'
alias c='clear'
alias grep='grep --color=auto'
alias gitlog="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"

# Plugins stuff
# load zplug if it doesn't exist
[[ -d ~/.zplug ]] || {
    git clone https://github.com/b4b4r07/zplug ~/.zplug
}
source ~/.zplug/init.zsh
# Hacky way to load oh-my-zsh libs
zplug "robbyrussell/oh-my-zsh",            from:github, use:"lib/*.zsh", defer:0, ignore:oh-my-zsh.sh
# Install plugins
zplug "plugins/git", from:oh-my-zsh, if:"hash git"
zplug "Seinh/git-prune", from:github, if:"hash git"
zplug "zsh-users/zsh-syntax-highlighting", from:github, defer:3
# Theme!
zplug "denysdovhan/spaceship-zsh-theme",   from:github, as:theme
# Actually install plugins, prompt user input
if ! zplug check --verbose; then
    printf "Install zplug plugins? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load

# source fzf if it exists
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source ~/.aliases
if [[ -f ~/.aliases-local ]];then
    source ~/.aliases-local
fi

# Source pyenv init if it exists
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi

if [[ -n "$BENCHMARK" ]];then
    zprof > "$HOME/.zsh_benchmark"
fi

# added by travis gem
[ -f /Users/eli9558/.travis/travis.sh ] && source /Users/eli9558/.travis/travis.sh
